version: '3.4'

services:
  db:
    image: projeto-social-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123mudar
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: projeto_social_api
    ports:
      - 3306:3306
    networks:
      - tgw-network
      
  projeto-social-api:
    image: projeto-social-api
    build:
      context: .
      dockerfile: ProjetoSocialAPI/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44324:80
    depends_on:
      - db
    networks:
      - tgw-network
networks:
  tgw-network:
    driver: bridge